import "../pages/mainPage/components.css"
export { default as BoshSahifa } from "../pages/bosh_sahifa/BoshSahifa"
export { default as Clients } from "../pages/clients/Clients"
export { default as Currency } from "../pages/currency/Currency"
export { default as Debts } from "../pages/debts/Debts"
export { default as Deliver } from "../pages/deliver/Deliver"
export { default as Employees } from "../pages/employees/Employees"
export { default as Goods } from "../pages/goods/Goods"
export { default as Home } from "../pages/home/Home"
export { default as Login } from "../pages/login/Login"
export { default as MainPage } from "../pages/mainPage/MainPage"
export { default as PageNotFound } from "../pages/pageNotFound/PageNotFound"
export { default as Products } from "../pages/produtcs/Products"
export { default as Reports } from "../pages/reports/Reports"
export { default as Return } from "../pages/return/Return"
export { default as Settings } from "../pages/settings/Settings"
export { default as Store } from "../pages/store/Store"
