name: Melissa Front Deploy (Dev)

on:
  push:
    branches:
      - development   # faqat dev branch push bo‘lganda

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.FRONT_SSH_KEY }}

      - name: Deploy Frontend to Dev Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.FRONT_SSH_USER }}@${{ secrets.FRONT_SSH_HOST }} << 'EOF'
            set -e
            echo "📦 Pulling latest frontend code..."
            cd ${{ secrets.FRONT_APP_PATH }}
            git restore .
            git pull origin development
            echo "📦 Installing dependencies..."
            npm install
            echo "🏗️ Building frontend..."
            npm run build
            echo "🚀 Deploying to /var/www/html..."
            sudo rm -rf /var/www/html/*
            sudo cp -r build/* /var/www/html/
            echo "✅ Frontend deployed successfully!"
          EOF
